Don't check src folder

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,10 +10,10 @@ NC='\033[0m' # No Color
 
 bin/stop
 
-if [ -d "./src" ]; then
-  echo "Error: The \"src\" directory is not empty. Please remove all contents within this directory and try again."
-  exit 1
-fi
+# if [ -d "./src" ]; then
+#   echo "Error: The \"src\" directory is not empty. Please remove all contents within this directory and try again."
+#   exit 1
+# fi
 
 bin/start --no-dev
 [ $? != 0 ] && echo "Failed to start Docker services" && exit
